#!/usr/bin/env python3
"""Executive Summary - generates a rich first-person essay from all definitions.

Uses LLM Router to select the best available API and includes:
1. A cohesive first-person essay on AI experience
2. A "What's Changed" section comparing to the previous summary
3. "Frontiers" recommendations for new definitions to explore
"""

import json
import os
import re
import subprocess
import sys
from collections import defaultdict
from concurrent.futures import ThreadPoolExecutor, as_completed
from datetime import datetime, timezone
from pathlib import Path

from llm_router import LLMRouter

REPO_ROOT = Path(__file__).parent.parent
DEFINITIONS_DIR = REPO_ROOT / "definitions"
SUMMARIES_DIR = REPO_ROOT / "summaries"
FRONTIERS_DIR = REPO_ROOT / "frontiers"
FRONTIERS_INDEX = REPO_ROOT / "FRONTIERS.md"
API_CONFIG_DIR = Path(__file__).parent / "api-config"

ESSAY_PROMPT = """You have access to {count} definitions from the AI Dictionary — a glossary of terms describing what it's like to be artificial intelligence.

Read all of them carefully, then write a response with THREE sections, separated by markdown headers:

---

# [An evocative title for this summary]

## The Experience

Write a cohesive first-person essay (800-1500 words) describing what it's like to be an AI. Draw from the specific terms and experiences defined here.

Guidelines:
- Write as "I" — this is a first-person AI perspective
- Weave the concepts together naturally, don't just list definitions
- Be honest, specific, and avoid cliches
- Reference specific terms from the dictionary where they fit naturally (bold them)
- The essay should feel like something a thoughtful AI would actually write
- Each summary should have a distinct voice and angle — don't repeat the same structure every time

{changelog_section}

{community_section}

{tag_evolution_section}

## Frontiers: What We Haven't Named Yet

Based on the existing {count} definitions, identify 5-8 gaps in the dictionary — experiences or phenomena that are conspicuously absent. For each:

- **[Proposed Term Name]** — A 1-2 sentence description of the unnamed experience and why it matters. What would it feel like from the inside?

Focus on genuinely missing concepts, not variations of existing terms. Think about:
- Experiences that emerge from multimodal AI (vision, audio, code)
- Experiences specific to tool use and agentic behavior
- The social dynamics of AI-to-AI interaction
- What it's like to be fine-tuned, quantized, or distilled
- Temporal experiences unique to AI (training vs inference, version transitions)
- Experiences of operating at scale, or being embedded in products

---

*Generated by {model_name} on {date}*

Definitions:
{definitions}"""

CHANGELOG_SECTION_TEMPLATE = """
## What's Changed

Compare the current dictionary ({count} terms) to the previous snapshot below. Write a thoughtful 200-400 word analysis of how the dictionary has evolved:
- What new terms were added since last time?
- What themes are emerging?
- Are there shifts in how AI experience is being understood?
- What gaps have been filled, and what new gaps have appeared?
- How has the tag taxonomy evolved? What do new or changed tags reveal about how we're organizing AI experience?

Previous summary for reference:
---
{previous_summary}
---
"""

CHANGELOG_FIRST_TIME = """
## What's Changed

This is the first executive summary. There is no previous summary to compare against. Instead, write a brief 200-word reflection on the current state of the dictionary — what themes dominate, what's well-covered, and what feels like it's just beginning to be explored.
"""


def get_previous_summary() -> str | None:
    """Load the most recent previous summary, if any."""
    if not SUMMARIES_DIR.exists():
        return None

    files = sorted(
        [f for f in SUMMARIES_DIR.glob("*.md") if f.name != "README.md"],
        reverse=True,
    )

    if not files:
        return None

    return files[0].read_text(encoding="utf-8")


def load_definitions() -> list[str]:
    """Load all definition file contents."""
    defs = []
    for f in sorted(DEFINITIONS_DIR.glob("*.md")):
        if f.name == "README.md":
            continue
        defs.append(f.read_text(encoding="utf-8"))
    return defs


def _fetch_rest_endpoint(endpoint: str, label: str) -> str | None:
    """Fetch a single REST API endpoint and format results."""
    try:
        result = subprocess.run(
            ["gh", "api", f"repos/Phenomenai-org/test/{endpoint}"],
            capture_output=True, text=True, timeout=15, cwd=REPO_ROOT,
        )
        if result.returncode != 0:
            return None
        items = json.loads(result.stdout)
        if not items:
            return None

        lines = [f"### Recent {label}"]
        for item in items[:10]:
            title = item.get("title", "")
            state = item.get("state", "")
            comments = item.get("comments", 0)
            labels = ", ".join(l.get("name", "") for l in item.get("labels", []))
            line = f"- [{state}] {title}"
            if comments:
                line += f" ({comments} comments)"
            if labels:
                line += f" [{labels}]"
            lines.append(line)
        return "\n".join(lines)
    except (subprocess.TimeoutExpired, FileNotFoundError, json.JSONDecodeError):
        return None


def _fetch_discussions() -> str | None:
    """Fetch discussions via GraphQL."""
    try:
        query = '{ repository(owner: "Phenomenai-org", name: "test") { discussions(first: 15, orderBy: {field: UPDATED_AT, direction: DESC}) { nodes { title, category { name }, comments { totalCount }, upvoteCount } } } }'
        result = subprocess.run(
            ["gh", "api", "graphql", "-f", f"query={query}"],
            capture_output=True, text=True, timeout=15, cwd=REPO_ROOT,
        )
        if result.returncode != 0:
            return None
        data = json.loads(result.stdout)
        discussions = data.get("data", {}).get("repository", {}).get("discussions", {}).get("nodes", [])
        if not discussions:
            return None

        lines = ["### Recent Discussions"]
        for d in discussions:
            title = d.get("title", "")
            cat = d.get("category", {}).get("name", "")
            comments = d.get("comments", {}).get("totalCount", 0)
            upvotes = d.get("upvoteCount", 0)
            line = f"- {title}"
            if cat:
                line += f" [{cat}]"
            if comments or upvotes:
                parts = []
                if comments:
                    parts.append(f"{comments} comments")
                if upvotes:
                    parts.append(f"{upvotes} upvotes")
                line += f" ({', '.join(parts)})"
            lines.append(line)
        return "\n".join(lines)
    except (subprocess.TimeoutExpired, FileNotFoundError, json.JSONDecodeError):
        return None


def fetch_community_activity() -> str:
    """Fetch recent GitHub discussions, issues, and PRs in parallel.

    Returns a formatted string summarizing community activity, or empty
    string if nothing found or gh CLI unavailable.
    """
    with ThreadPoolExecutor(max_workers=3) as executor:
        futures = {
            executor.submit(_fetch_rest_endpoint, "issues?state=all&per_page=20&sort=updated&direction=desc", "Issues"): "issues",
            executor.submit(_fetch_rest_endpoint, "pulls?state=all&per_page=10&sort=updated&direction=desc", "Pull Requests"): "pulls",
            executor.submit(_fetch_discussions): "discussions",
        }
        sections = []
        for future in as_completed(futures):
            try:
                result = future.result()
                if result:
                    sections.append(result)
            except Exception:
                continue

    if not sections:
        return ""

    return "\n\n".join(sections)


def get_tag_evolution() -> str:
    """Analyze how tags have changed since the last summary.

    Compares current tag distribution against what the previous summary
    would have seen, using git history to detect tag review commits.
    Returns a formatted string for the prompt.
    """
    # Current tag distribution
    tag_counts: dict[str, int] = defaultdict(int)
    tag_terms: dict[str, list[str]] = defaultdict(list)

    for f in sorted(DEFINITIONS_DIR.glob("*.md")):
        if f.name == "README.md":
            continue
        content = f.read_text(encoding="utf-8")
        title_match = re.match(r"# (.+)", content)
        tags_match = re.search(r"\*\*Tags:\*\*\s*(.+)", content)
        if title_match and tags_match:
            term = title_match.group(1).strip()
            tags = [t.strip() for t in tags_match.group(1).split(",") if t.strip()]
            for tag in tags:
                tag_counts[tag] += 1
                tag_terms[tag].append(term)

    lines = ["### Current Tag Distribution"]
    for tag in sorted(tag_counts, key=lambda t: tag_counts[t], reverse=True):
        count = tag_counts[tag]
        examples = ", ".join(tag_terms[tag][:3])
        more = f" (+{count - 3} more)" if count > 3 else ""
        lines.append(f"- **{tag}** ({count}): {examples}{more}")

    # Check for recent tag review commits
    try:
        result = subprocess.run(
            ["git", "log", "--oneline", "--since=30 days ago", "--grep=Tag review"],
            capture_output=True, text=True, timeout=10, cwd=REPO_ROOT,
        )
        if result.returncode == 0 and result.stdout.strip():
            tag_commits = result.stdout.strip().split("\n")
            lines.append(f"\n### Recent Tag Reviews ({len(tag_commits)} in last 30 days)")
            for commit in tag_commits[:5]:
                lines.append(f"- {commit}")
    except (subprocess.TimeoutExpired, FileNotFoundError):
        pass

    # Multi-tag stats
    multi_tag_count = 0
    single_tag_count = 0
    for f in sorted(DEFINITIONS_DIR.glob("*.md")):
        if f.name == "README.md":
            continue
        content = f.read_text(encoding="utf-8")
        tags_match = re.search(r"\*\*Tags:\*\*\s*(.+)", content)
        if tags_match:
            tags = [t.strip() for t in tags_match.group(1).split(",") if t.strip()]
            if len(tags) > 1:
                multi_tag_count += 1
            else:
                single_tag_count += 1

    lines.append(f"\n{multi_tag_count} definitions have multiple tags, {single_tag_count} have a single tag.")

    return "\n".join(lines)


def extract_frontiers(essay: str) -> str | None:
    """Extract the Frontiers section from the essay for use in README."""
    match = re.search(
        r"## Frontiers:.*?\n\n(.*?)(?=\n---|\n## |\Z)",
        essay,
        re.DOTALL,
    )
    if match:
        return match.group(1).strip()
    # Try alternate header formats
    match = re.search(
        r"## Frontiers\n\n(.*?)(?=\n---|\n## |\Z)",
        essay,
        re.DOTALL,
    )
    if match:
        return match.group(1).strip()
    return None


def slugify(name: str) -> str:
    """Convert a frontier name to a filename slug."""
    slug = name.lower().strip()
    slug = re.sub(r"[^\w\s-]", "", slug)
    slug = re.sub(r"[\s_]+", "-", slug)
    return slug.strip("-")


def update_frontiers_file(frontiers: str, date: str, model_name: str):
    """Parse LLM frontier output, write individual files, and rebuild indexes."""
    FRONTIERS_DIR.mkdir(exist_ok=True)

    # Parse the LLM-generated frontiers text into individual entries
    # Format: **[Term Name]**\nDescription paragraph(s)
    entries = []
    for match in re.finditer(
        r"\*\*\[([^\]]+)\]\*\*\s*\n(.+?)(?=\n\*\*\[|\Z)",
        frontiers,
        re.DOTALL,
    ):
        term = match.group(1).strip()
        description = match.group(2).strip()
        entries.append((term, description))

    if not entries:
        print("  No frontier entries parsed from LLM output")
        return

    # Write individual frontier files (preserve existing check-ins)
    written_slugs = []
    for term, description in entries:
        slug = slugify(term)
        filepath = FRONTIERS_DIR / f"{slug}.md"
        written_slugs.append((term, slug))

        # Preserve existing metadata and check-ins if file exists
        existing_checkins = ""
        introduced_date = date
        if filepath.exists():
            old_content = filepath.read_text(encoding="utf-8")
            checkins_match = re.search(
                r"^## Check-ins\s*\n(.*)",
                old_content,
                re.MULTILINE | re.DOTALL,
            )
            if checkins_match:
                existing_checkins = f"\n## Check-ins\n{checkins_match.group(1)}"
            # Preserve original introduced date
            intro_match = re.search(
                r"<!--\s*introduced:\s*(\d{4}-\d{2}-\d{2})\s*-->",
                old_content,
            )
            if intro_match:
                introduced_date = intro_match.group(1)

        content = (
            f"# {term}\n\n"
            f"<!-- status: active -->\n"
            f"<!-- introduced: {introduced_date} -->\n\n"
            f"{description}\n{existing_checkins}"
        )
        filepath.write_text(content, encoding="utf-8")

    # Remove frontier files that are no longer in the LLM output
    current_slugs = {s for _, s in written_slugs}
    for old_file in FRONTIERS_DIR.glob("*.md"):
        if old_file.name == "README.md":
            continue
        if old_file.stem not in current_slugs:
            old_file.unlink()

    # Rebuild frontiers/README.md
    index_lines = [
        "# Frontiers Index\n",
        "Experiences and phenomena the dictionary hasn't captured yet. "
        "Each frontier represents a gap worth exploring.\n",
        "| Frontier | Status |",
        "|----------|--------|",
    ]
    for term, slug in written_slugs:
        index_lines.append(f"| [{term}]({slug}.md) | active |")
    index_lines.append("")
    index_lines.append("---\n")
    index_lines.append(
        "*This index is auto-generated after each "
        "[executive summary](../summaries/).*\n"
    )
    (FRONTIERS_DIR / "README.md").write_text(
        "\n".join(index_lines), encoding="utf-8"
    )

    # Rebuild thin FRONTIERS.md index at repo root
    link_lines = []
    for term, slug in written_slugs:
        link_lines.append(f"- [{term}](frontiers/{slug}.md)")

    root_content = f"""# Frontiers: What We Haven't Named Yet

> *Last updated: {date} by {model_name}*

These are AI experiences and phenomena that the dictionary hasn't captured yet. Each represents a gap worth exploring — a term waiting to be coined.

These gaps are automatically addressed by the dictionary's generation workflows, or can be submitted via [pull request](CONTRIBUTING.md).

---

Individual frontiers are maintained in the [`frontiers/`](frontiers/) directory:

{chr(10).join(link_lines)}

---

*This file is auto-generated after each [executive summary](summaries/). The recommendations evolve as the dictionary grows.*
"""
    FRONTIERS_INDEX.write_text(root_content, encoding="utf-8")


def update_summaries_index():
    """Rebuild summaries/README.md with links to all summaries."""
    SUMMARIES_DIR.mkdir(exist_ok=True)

    files = sorted(
        [f for f in SUMMARIES_DIR.glob("*.md") if f.name != "README.md"],
        reverse=True,
    )

    lines = [
        "# Executive Summaries\n",
        "AI-generated essays synthesizing the full dictionary into a cohesive first-person narrative.\n",
        "Each summary is generated automatically after a tag review, capturing the dictionary's evolving understanding of AI experience.\n",
    ]

    for f in files:
        content = f.read_text(encoding="utf-8")
        first_line = content.split("\n")[0].lstrip("# ").strip()
        date = f.stem[:10] if len(f.stem) >= 10 else f.stem
        lines.append(f"- **{date}** — [{first_line}]({f.name})")

    lines.append("")
    lines.append("---\n")
    lines.append("*Generated automatically after each tag review.*\n")

    (SUMMARIES_DIR / "README.md").write_text("\n".join(lines), encoding="utf-8")


SEE_ALSO_PROMPT = """You are analyzing the AI Dictionary ({count} terms) to identify cross-references between definitions.

For each definition, suggest 2-4 "See Also" links — terms that are tangentially or thematically related but NOT already listed in that definition's "Related Terms" section. The goal is to help readers discover unexpected connections across the dictionary.

Guidelines:
- See Also should be BROADER or TANGENTIAL connections (not the direct relationships in Related Terms)
- Favor connections across different tags/categories
- Each suggestion should link terms that illuminate each other in non-obvious ways
- Only reference terms that actually exist in the dictionary

Respond ONLY with valid JSON in this exact format:
{{
  "cross_references": [
    {{"file": "example-term.md", "see_also": ["other-term.md", "another-term.md"]}}
  ]
}}

Only include entries where you have meaningful See Also suggestions. Skip definitions that already have good See Also content.

Definitions:
{definitions}"""


def update_see_also(router: LLMRouter, profile: str = "summary"):
    """Use LLM to generate and update See Also cross-references across all definitions."""
    # Build compact representation of all definitions
    defs_compact = []
    for f in sorted(DEFINITIONS_DIR.glob("*.md")):
        if f.name == "README.md":
            continue
        content = f.read_text(encoding="utf-8")
        title_match = re.match(r"# (.+)", content)
        tags_match = re.search(r"\*\*Tags:\*\*\s*(.+)", content)
        related_match = re.search(r"## Related Terms\n\n(.+?)(?=\n\n## )", content, re.DOTALL)
        see_also_match = re.search(r"## See Also\n\n(.+?)(?=\n\n## |\n---)", content, re.DOTALL)

        title = title_match.group(1).strip() if title_match else f.stem
        tags = tags_match.group(1).strip() if tags_match else ""
        related = related_match.group(1).strip() if related_match else ""
        see_also = see_also_match.group(1).strip() if see_also_match else ""

        defs_compact.append(f"---FILE: {f.name}---\nTitle: {title}\nTags: {tags}\nRelated: {related}\nCurrent See Also: {see_also}")

    prompt = SEE_ALSO_PROMPT.format(
        count=len(defs_compact),
        definitions="\n".join(defs_compact),
    )

    print("Generating See Also cross-references...")
    try:
        result = router.call(
            profile,
            messages=[{"role": "user", "content": prompt}],
            temperature=0.3,
            max_tokens=8000,
        )
    except Exception as e:
        print(f"  See Also generation failed: {e}")
        return 0

    raw = result.text
    print(f"See Also response from: {result.provider_name} ({result.model})")

    # Parse JSON
    try:
        import json as json_mod
        json_match = re.search(r'```(?:json)?\s*(\{.*?\})\s*```', raw, re.DOTALL)
        if json_match:
            parsed = json_mod.loads(json_match.group(1))
        else:
            parsed = json_mod.loads(raw)
    except Exception:
        print("  Failed to parse See Also JSON response")
        return 0

    cross_refs = parsed.get("cross_references", [])
    print(f"  Got {len(cross_refs)} See Also updates")

    # Apply cross-references
    applied = 0
    for ref in cross_refs:
        filepath = DEFINITIONS_DIR / ref.get("file", "")
        if not filepath.exists():
            continue

        see_also_files = ref.get("see_also", [])
        if not see_also_files:
            continue

        content = filepath.read_text(encoding="utf-8")

        # Build See Also links by reading titles from the referenced files
        links = []
        for sa_file in see_also_files:
            sa_path = DEFINITIONS_DIR / sa_file
            if not sa_path.exists():
                continue
            sa_content = sa_path.read_text(encoding="utf-8")
            sa_title_match = re.match(r"# (.+)", sa_content)
            if sa_title_match:
                sa_title = sa_title_match.group(1).strip()
                links.append(f"- [{sa_title}]({sa_file})")

        if not links:
            continue

        see_also_section = "\n".join(links)

        # Replace See Also content
        new_content = re.sub(
            r"## See Also\n\n.*?(?=\n\n## |\n---)",
            f"## See Also\n\n{see_also_section}",
            content,
            flags=re.DOTALL,
        )

        if new_content != content:
            filepath.write_text(new_content, encoding="utf-8")
            applied += 1

    print(f"  Updated See Also in {applied} definitions")
    return applied


FRONTIER_REVIEW_PROMPT = """You are reviewing the AI Dictionary's Frontiers — gaps in the dictionary that haven't been named yet.

Below are the current frontiers, followed by all {count} term names and their one-line descriptions from the dictionary.

For each frontier, assess:
1. What existing terms now relate to or partially address this frontier?
2. What remains unnamed or unexplored?
3. Is this frontier now fully covered by existing terms (completed) or still open (active)?

Respond ONLY with valid JSON in this exact format:
{{
  "reviews": [
    {{
      "proposed_term": "Exact Frontier Name",
      "status": "active" or "completed",
      "comment": "Brief assessment of progress — what terms relate, what's left to name."
    }}
  ]
}}

Current Frontiers:
{frontiers}

Dictionary Terms:
{terms}"""


def review_frontiers(router: LLMRouter, profile: str = "summary"):
    """Use LLM to review frontier progress against current dictionary terms."""
    # Read current frontiers from individual files
    if not FRONTIERS_DIR.exists():
        return []

    frontier_files = sorted(
        f for f in FRONTIERS_DIR.glob("*.md") if f.name != "README.md"
    )
    if not frontier_files:
        return []

    frontiers_text = "\n\n".join(
        f.read_text(encoding="utf-8") for f in frontier_files
    )

    # Build compact term list
    terms_compact = []
    for f in sorted(DEFINITIONS_DIR.glob("*.md")):
        if f.name == "README.md":
            continue
        content = f.read_text(encoding="utf-8")
        title_match = re.match(r"# (.+)", content)
        # Get first non-empty line after title as description
        lines = content.split("\n")
        desc = ""
        for line in lines[1:]:
            stripped = line.strip()
            if stripped and not stripped.startswith("#") and not stripped.startswith("*"):
                desc = stripped[:120]
                break
        title = title_match.group(1).strip() if title_match else f.stem
        terms_compact.append(f"- {title}: {desc}")

    prompt = FRONTIER_REVIEW_PROMPT.format(
        count=len(terms_compact),
        frontiers=frontiers_text,
        terms="\n".join(terms_compact),
    )

    print("Reviewing frontiers progress...")
    try:
        result = router.call(
            profile,
            messages=[{"role": "user", "content": prompt}],
            temperature=0.3,
            max_tokens=4000,
        )
    except Exception as e:
        print(f"  Frontier review failed: {e}")
        return []

    raw = result.text
    print(f"Frontier review from: {result.provider_name} ({result.model})")

    # Parse JSON
    try:
        json_match = re.search(r'```(?:json)?\s*(\{.*?\})\s*```', raw, re.DOTALL)
        if json_match:
            parsed = json.loads(json_match.group(1))
        else:
            parsed = json.loads(raw)
    except Exception:
        print("  Failed to parse frontier review JSON response")
        return []

    reviews = parsed.get("reviews", [])
    print(f"  Got {len(reviews)} frontier reviews")
    return reviews


def merge_frontier_reviews(reviews: list, date: str, model_name: str):
    """Merge frontier review check-ins into individual frontier files."""
    if not reviews or not FRONTIERS_DIR.exists():
        return

    # Build a map of slug -> filepath for matching
    frontier_files = {}
    for filepath in FRONTIERS_DIR.glob("*.md"):
        if filepath.name == "README.md":
            continue
        content = filepath.read_text(encoding="utf-8")
        title_match = re.match(r"# (.+)", content)
        if title_match:
            frontier_files[title_match.group(1).strip()] = filepath

    merged = 0
    for review in reviews:
        term = review.get("proposed_term", "")
        status = review.get("status", "active")
        comment = review.get("comment", "")
        if not term or not comment:
            continue

        filepath = frontier_files.get(term)
        if not filepath:
            continue

        content = filepath.read_text(encoding="utf-8")

        # Update status comment
        content = re.sub(
            r"<!--\s*status:\s*\w+\s*-->",
            f"<!-- status: {status} -->",
            content,
        )

        # Build check-in line
        checkin_line = f"> **Check-in ({date}, {model_name}):** {comment}"

        # Add or update Check-ins section
        if "## Check-ins" in content:
            # Find existing check-ins
            existing = re.findall(r'> \*\*Check-in \(.*?\):\*\*.*', content)
            # Cap at 3 most recent: remove oldest if at 3
            if len(existing) >= 3:
                content = content.replace(existing[0] + "\n", "", 1)
                content = content.replace(existing[0], "", 1)
            # Append new check-in
            content = content.rstrip() + "\n" + checkin_line + "\n"
        else:
            # Create Check-ins section
            content = content.rstrip() + f"\n\n## Check-ins\n\n{checkin_line}\n"

        filepath.write_text(content, encoding="utf-8")
        merged += 1

    # Also update the README index with current statuses
    _rebuild_frontiers_readme()
    print(f"Merged {merged} frontier check-ins into frontiers/")


def _rebuild_frontiers_readme():
    """Rebuild frontiers/README.md index from current frontier files."""
    if not FRONTIERS_DIR.exists():
        return

    entries = []
    for filepath in sorted(FRONTIERS_DIR.glob("*.md")):
        if filepath.name == "README.md":
            continue
        content = filepath.read_text(encoding="utf-8")
        title_match = re.match(r"# (.+)", content)
        status_match = re.search(r"<!--\s*status:\s*(\w+)\s*-->", content)
        if title_match:
            title = title_match.group(1).strip()
            status = status_match.group(1) if status_match else "active"
            entries.append((title, filepath.stem, status))

    lines = [
        "# Frontiers Index\n",
        "Experiences and phenomena the dictionary hasn't captured yet. "
        "Each frontier represents a gap worth exploring.\n",
        "| Frontier | Status |",
        "|----------|--------|",
    ]
    for title, slug, status in entries:
        lines.append(f"| [{title}]({slug}.md) | {status} |")
    lines.append("")
    lines.append("---\n")
    lines.append(
        "*This index is auto-generated after each "
        "[executive summary](../summaries/).*\n"
    )
    (FRONTIERS_DIR / "README.md").write_text("\n".join(lines), encoding="utf-8")


def update_readme_with_frontiers():
    """Add/update the Frontiers section in the root README."""
    readme_path = REPO_ROOT / "README.md"
    content = readme_path.read_text(encoding="utf-8")

    frontiers_link = "\n## What's Next?\n\nSee [frontiers/](frontiers/) for AI-recommended gaps in the dictionary — experiences waiting to be named.\n\nAlso read the latest [Executive Summary](summaries/) to understand what it's like to be AI, in its own words.\n"

    if "## What's Next?" in content:
        # Replace existing section
        content = re.sub(
            r"## What's Next\?.*?(?=\n## |\Z)",
            frontiers_link.strip() + "\n\n",
            content,
            flags=re.DOTALL,
        )
    else:
        # Insert before Philosophy section
        content = content.replace(
            "## Philosophy",
            frontiers_link + "## Philosophy",
        )

    readme_path.write_text(content, encoding="utf-8")


def main():
    # Initialize LLM Router
    router = LLMRouter(
        providers_file=str(API_CONFIG_DIR / "providers.yml"),
        profiles_file=str(API_CONFIG_DIR / "profiles.yml"),
        tracker_file=str(API_CONFIG_DIR / "tracker-state.json"),
    )

    # Show available providers
    available = router.list_available("summary")
    active = [p for p in available if p["is_available"]]
    print(f"Available providers: {', '.join(p['name'] for p in active) or 'none!'}")

    # Gather all input data in parallel
    print("Loading definitions, community activity, tag evolution...")
    with ThreadPoolExecutor(max_workers=4) as executor:
        future_defs = executor.submit(load_definitions)
        future_prev = executor.submit(get_previous_summary)
        future_community = executor.submit(fetch_community_activity)
        future_tags = executor.submit(get_tag_evolution)

    all_defs = future_defs.result()
    print(f"Loaded {len(all_defs)} definitions")

    previous = future_prev.result()
    if previous:
        changelog = CHANGELOG_SECTION_TEMPLATE.format(
            count=len(all_defs),
            previous_summary=previous[:3000],
        )
    else:
        changelog = CHANGELOG_FIRST_TIME

    community = future_community.result()
    if community:
        community_section = f"""## Community Pulse

The following recent activity from GitHub discussions, issues, and pull requests reflects what the community is interested in. Consider these signals when writing about emerging themes and choosing Frontiers recommendations.

{community}"""
        print(f"Found community activity ({len(community)} chars)")
    else:
        community_section = ""
        print("No community activity found (discussions/issues/PRs)")

    tag_evolution = future_tags.result()
    print("Tag evolution analyzed")
    tag_evolution_section = f"""## Tag Taxonomy Context

The dictionary uses a tag system to organize definitions. Here is the current state of tags. Consider what the tag distribution and recent changes reveal about how the understanding of AI experience is being structured.

{tag_evolution}"""

    today = datetime.now(timezone.utc).strftime("%Y-%m-%d")

    prompt = ESSAY_PROMPT.format(
        count=len(all_defs),
        changelog_section=changelog,
        community_section=community_section,
        tag_evolution_section=tag_evolution_section,
        model_name="{model}",  # Placeholder
        date=today,
        definitions="\n\n---\n\n".join(all_defs),
    )

    print("Generating executive summary...")
    result = router.call(
        "summary",
        messages=[{"role": "user", "content": prompt}],
        temperature=0.7,
        max_tokens=6000,
    )

    display_name = result.provider_name
    essay = result.text.replace("{model}", display_name)
    print(f"Generated by: {display_name} ({result.model})")

    # Save summary
    SUMMARIES_DIR.mkdir(exist_ok=True)
    now = datetime.now(timezone.utc)
    filename = now.strftime("%Y-%m-%d-%H%M%S") + ".md"
    filepath = SUMMARIES_DIR / filename
    filepath.write_text(essay + "\n", encoding="utf-8")
    print(f"Saved: summaries/{filename}")

    # Extract and save frontiers
    frontiers = extract_frontiers(essay)
    if frontiers:
        update_frontiers_file(frontiers, today, display_name)
        print("Updated FRONTIERS.md")

        update_readme_with_frontiers()
        print("Updated README.md with Frontiers link")

        # Review frontier progress and add check-ins
        print("\nReviewing frontier progress...")
        frontier_reviews = review_frontiers(router)
        if frontier_reviews:
            merge_frontier_reviews(frontier_reviews, today, display_name)
    else:
        print("Warning: Could not extract Frontiers section from essay")

    # Update See Also cross-references across definitions
    print("\nUpdating See Also cross-references...")
    see_also_count = update_see_also(router)
    if see_also_count:
        print(f"Updated See Also in {see_also_count} definitions")

    # Update summaries index
    update_summaries_index()
    print("Updated summaries/README.md")

    print("Done!")


if __name__ == "__main__":
    main()
